const sampleArr = [
    {
        "name": "Steve Jobs", 
        "reasonForKnowing": "Co-founder of Apple", 
        "education": "",
        "work": "CEO of Apple",
        "hometown": "Cupertino",
        "birthday": "",
        "interests": "Computers, Design",
        "mutualFriends": "Woz",
        "birthMonth": "May",
        "birthDate": 30,
        "additionalInfo": "2021-06-03",
        "createdAt": 1621912526147,
        "id": "1621912526147_44"
    },
    {
        "name": "Tupac", 
        "reasonForKnowing": "Prolific rapper", 
        "education": "",
        "work": "",
        "hometown": "",
        "birthMonth": "September",
        "birthDate": 3,
        "interests": "",
        "mutualFriends": "",
        "additionalInfo": "",
        "createdAt": 1621913088492,
        "id": "1621913088492_32"
    },
    {
        "name": "Biggie", 
        "reasonForKnowing": "Another legendary, prolific rapper", 
        "education": "",
        "work": "",
        "hometown": "",
        "birthMonth": "May",
        "birthDate": 23,
        "interests": "",
        "mutualFriends": "",
        "additionalInfo": "",
        "createdAt": 1621913909456,
        "id": "1621913909456_98"
    },
    {
        "name": "LeBron James", 
        "reasonForKnowing": "Lakeshow", 
        "education": "",
        "work": "",
        "hometown": "",
        "birthMonth": "June",
        "birthDate": 1,
        "interests": "",
        "mutualFriends": "",
        "additionalInfo": "",
        "createdAt": 1621914068502,
        "id": "1621914068502_61"
    },
    {
        "name": "Barack Obama", 
        "reasonForKnowing": "Used to be president.", 
        "education": "",
        "work": "",
        "hometown": "",
        "birthMonth": "August",
        "birthDate": 4,
        "interests": "",
        "mutualFriends": "",
        "additionalInfo": "",
        "createdAt": 1621914087244,
        "id": "1621914087244_76"
    },
    {
        "name": "Elon Musk", 
        "reasonForKnowing": "Met at a Mars conference", 
        "education": "",
        "work": "",
        "hometown": "",
        "birthMonth": "January",
        "birthDate": 1,
        "interests": "",
        "mutualFriends": "",
        "additionalInfo": "",
        "createdAt": 1621914097903,
        "id": "1621914097903_11"
    },
];

export {sampleArr};